security:
  encoders:
    AA\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       [ROLE_CLIENT, ROLE_PHOTOGRAPHE]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      id: fos_user.user_provider.username_email

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Firewall principal
    main:
      pattern:      ^/
      anonymous:    true
      provider:     main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
      logout:
        path:       fos_user_security_logout
        target:     aa_base_accueil
      remember_me:
        secret:     %secret% # %secret% est un paramètre de parameter

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
